### ISSUE TITLE
some questions about the model

### ISSUE THREAD

**Issue by whySnowwW** [InnovArul/vidreid_cosegmentation#1]
in cosam.py,there is a function get_channelwise_attention , i wonder what the input t b mean?
def get_channelwise_attention(self, feat_maps, b, t):
i want to apply or get the cosam in fine grain task, but i find myself troublesome understanding the whole task

**Comment by InnovArul** [comment]
Hi,

In the function `get_channelwise_attention(self, feat_maps, b, t)`, the parameters mean the following: 
`feat_maps` = feature maps of all frames from the videos. i.e., dimension is `(b*t) x c x h x w`. here: `b` = number of videos in the batch, `t` = number of frames in each video (it is assumed that each video has equal number of frames), `c, h, w` = channels, height, width of feature maps.

`b` = number of videos in the batch, 
`t` = number of frames in each video.

`b, t` are just passed to reshape the `feat_maps` if needed.

Hope it helps!

**Comment by whySnowwW** [comment]
Thank you very much! I just verified your code based on the thought you metioned ,and i just want  to make sure if it is suitable to use the cosam part in a fine grain task?

**Comment by InnovArul** [comment]
Can you elaborate on the task a bit? Maybe I am not aware of the task that you are talking about. 
In my observation, COSAM was able to highlight common regions in the frames (with respect to particular task). i.e., person and assessories for person re-id. 

With this in mind, you may think if it is applicable for your task.

**Comment by InnovArul** [comment]
I will close the issue. Pl. reopen it if you have questions again.
